export const LOGIN = "LOGIN";
export const CLOSE = "CLOSE";

export const CAPTURE = "CAPTURE";
export const RECEIVE_CAPTURED_IMAGE = "RECEIVE_CAPTURED_IMAGE";
export const PROCESS_CAPTURED_IMAGE = "PROCESS_CAPTURED_IMAGE";
export const FETCH_DIAGNOSIS_SUGGESTIONS = "FETCH_DIAGNOSIS_SUGGESTIONS";
export const RECEIVE_DIAGNOSIS_SUGGESTIONS = "FETCH_DIAGNOSIS_SUGGESTIONS";

export const ADD_CROP = "ADD_CROP";