export const LOGIN = "LOGIN";
export const CLOSE = "CLOSE";

export const CAPTURE = "CAPTURE";
export const RECEIVE_CAPTURED_IMAGE = "RECEIVE_CAPTURED_IMAGE";
export const PROCESS_CAPTURED_IMAGE = "PROCESS_CAPTURED_IMAGE";
export const FETCH_DIAGNOSIS_SUGGESTIONS = "FETCH_DIAGNOSIS_SUGGESTIONS";
export const RECEIVE_DIAGNOSIS_SUGGESTIONS = "FETCH_DIAGNOSIS_SUGGESTIONS";
export const EXAMINE_CROP = "EXAMINE_CROP";

export const ADD_CROP = "ADD_CROP";
export const UPDATE_CROP = "UPDATE_CROP";
export const FETCH_CROPSET = "FETCH_CROPSET";
export const RECEIVE_CROPSET = "RECEIVE_CROPSET";

export const FETCH_CROPLIST = "FETCH_CROPLIST";
export const RECEIVE_CROPLIST = "RECEIVE_CROPLIST";
export const CHANGE_PAGE = "CHANGE_PAGE";